config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get 'participa', to: 'pages#participate', as: 'participate'
  get 'vota', to: 'pages#vote', as: 'vote'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def participate
  end

  def vote
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kotexbolivia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <div class="col-sm-12 kotex-footer">
    <p>RENUEVA TU VUELTA A CLASES CON KOTEX</p>
  </div>
</html>

app/views/pages/home.html.erb
  <div class="col-sm-6 participate-column">
    <%= link_to participate_path do %>
      <h2>PARTICIPA</h2>
    <% end %>
    <div class="row">
      <div class="col-sm-6 girl-column">
        <%= image_tag 'girl.png', class: "girl-image" %>
      </div>
      <div class="col-sm-6">
        <p class="participate-text">
          SUBE UNA <span class="highlight">SELFIE</span> CON TU<br />
          <span class="highlight">KOTEX</span> FAVORITA<br />
          Y UNA FRASE<br />
          UTILIZANDO EL HASTHAG
          <span class="highlight">#NOTEDETENGAS</span><br />
          CONTANDO COMO<br />
          NO TE DETIENE<br />
          TU PRIMER DIA DE CLASES
        </p>
      </div>
    </div>
  </div>
  <div class="col-sm-6 vote-column">
    <%= link_to vote_path do %>
      <h2>VOTA</h2>
    <% end %>
  </div>

app/views/pages/participate.html.erb
<div class="col-sm-12 pink-page">
  <h2>REGISTRA TUS DATOS</h2>
  <%= image_tag 'gift_card.png' %>
</div>

app/views/pages/vote.html.erb
<div class="col-sm-12 pink-page">
  <h2>Vota</h2>
</div>